name: Angular CI

on:
  workflow_call:
    inputs:
      branch-name:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      build-folder: ${{ steps.set-output.outputs.build-folder }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Build Angular App
        run: npm run build -- --configuration production

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: angular-dist
          path: dist/vyracare-app-shell

      - name: Set build folder output
        id: set-output
        run: echo "build-folder=dist/vyracare-app-shell" >> $GITHUB_OUTPUT

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: angular-dist
          path: dist/vyracare-app-shell

      - name: Run unit tests
        run: npm run test -- --watch=false --browsers=ChromeHeadless
