name: Rollback

on:
  workflow_call:
    inputs:
      rollback-path:
        description: 'Versão do rollback (ex: /blue/20250914120000)'
        required: false
        type: string
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      S3_BUCKET_NAME:
        required: true
      CLOUDFRONT_ID:
        required: true
      AWS_REGION:
        required: false

jobs:
  rollback:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: ${{ secrets.AWS_REGION || 'us-east-1' }}
      S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
      CLOUDFRONT_ID: ${{ secrets.CLOUDFRONT_ID }}
    steps:
      - name: Configure AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Determine rollback version
        id: determine
        run: |
          if [ -n "${{ inputs.rollback-path }}" ]; then
            echo "ROLLBACK_PATH=${{ inputs.rollback-path }}" >> $GITHUB_ENV
          else
            LAST_BUILD=$(aws s3 ls s3://$S3_BUCKET_NAME/blue/ | awk '{print $2}' | sort | tail -n 1)
            ROLLBACK_PATH="/blue/$LAST_BUILD"
            echo "ROLLBACK_PATH=$ROLLBACK_PATH" >> $GITHUB_ENV
          fi
          echo "Rollback path: $ROLLBACK_PATH"

      - name: Swap CloudFront to rollback version
        run: |
          DISTRIBUTION_CONFIG=$(aws cloudfront get-distribution-config --id $CLOUDFRONT_ID)
          ETAG=$(echo $DISTRIBUTION_CONFIG | jq -r '.ETag')
          CONFIG=$(echo $DISTRIBUTION_CONFIG | jq '.DistributionConfig')
          UPDATED_CONFIG=$(echo $CONFIG | jq --arg path "$ROLLBACK_PATH" '.Origins.Items[0].OriginPath=$path')
          aws cloudfront update-distribution --id $CLOUDFRONT_ID --if-match $ETAG --distribution-config "$UPDATED_CONFIG"

      - name: Invalidate CloudFront cache
        run: |
          aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_ID --paths "/*"

      - name: Notify rollback complete
        run: echo "Rollback para $ROLLBACK_PATH realizado com sucesso."
